version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: student_schedule_postgres
    environment:
      POSTGRES_DB: student_schedule_dev
      POSTGRES_USER: student_user
      POSTGRES_PASSWORD: student_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student_user -d student_schedule_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: student_schedule_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
