# ~/codes/projects/student-schedule-app/backend/configs/config.yaml
server:
  port: 50051

database:
  host: localhost
  port: 5432
  user: student_user
  password: student_pass
  dbname: student_schedule_dev
  sslmode: disable

redis:
  addr: localhost:6379

scraper:
  base_url: "https://kcpt72.ru/schedule/"
  timeout: 30s
  # Список gid листов основного расписания
  main_schedule_gids: 
    - 1891807071
    # Добавьте сюда другие gid, найденные вручную
    # - 1234567890
  # gid листа изменений (по умолчанию 0)
  changes_gid: 0

jwt:
  secret: "NL4JYOtuA8kOiIrJSuAApUAVjZ8tlTIdOaQZ77TTnY4="
  expiration: 24h
